export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';


export const GETCARS='GETCARS';
export const GETCARS_SUCCESS='GETCARS_SUCCESS';
export const GETCARS_FAIL='GETCARS_FAIL';
export const GETONECAR='GETONECAR';
export const ADDCAR='ADDCAR';
// export const DELETECHAMBRES='DELETECHAMBRES';
// export const EDITCHAMBRES='EDITCHAMBRES';

export const GETHOTEL='GETHOTEL';
export const GETHOTEL_SUCCESS='GETHOTEL_SUCCESS';
export const GETHOTEL_FAIL='GETHOTEL_FAIL';
export const GETONEHOTEL='GETONEHOTEL';
export const ADDHOTEL='ADDHOTEL';

export const GETEVENTS='GETEVENTS';
export const GETEVENTS_SUCCESS='GETEVENTS_SUCCESS';
export const GETEVENTS_FAIL='GETEVENTS_FAIL';
export const GETONEEVENT='GETONEEVENT';
export const ADDEVENT='ADDEVENT';

export const GETRANDOS='GETRANDOS';
export const GETRANDOS_SUCCESS='GETRANDOS_SUCCESS';
export const GETRANDOS_FAIL='GETRANDOS_FAIL';
export const GETONERANDO='GETONERANDO';
export const ADDRANDO='ADDRANDO';

export const GETMAISON='GETMAISON';
export const GETMAISON_SUCCESS='GETMAISON_SUCCESS';
export const GETMAISON_FAIL='GETMAISON_FAIL';
export const GETONEMAISON='GETONEMAISON';
export const ADDMAISON='ADDMAISON';

